spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
        - id: company-server
          uri: lb://company-server
          predicates:
            - Path=/companies/**
        - id: hub-server
          uri: lb://hub-server
          predicates:
            - Path=/hubs/**
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/orders/**
      discovery:
        locator:
          enabled: true
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop ??? ???, ??? ?? ? ???? ?? ??? ??? ? ??
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: application/auth/docker-compose.yml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 8080

