spring:
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop ??? ???, ??? ?? ? ???? ?? ??? ??? ? ??
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: application/auth/docker-compose.yml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 8080

