services:

  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=animal'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=animal'
    ports:
      - '54322:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
