services:

  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=animal'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=animal'
    ports:
      - '54321:5432'
    volumes:
      - postgres_data_hub:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data_hub:
  redis_data:
