spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54322/animal
    username: animal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop 옵션이 있으며, 스프링 종료 시 컨테이너 종료 여부를 결정할 수 있음
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: application/order/docker-compose.yml



  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost
server:
  port: 8082


weather:
  service:
    key: ${WEATHER_KEY}

gemini:
  api:
    key: ${GEMINI_KEY}


slack:
  incoming-hook:
    url: https://hooks.slack.com/services/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

