# 상단의 다음으로 실행에서 dev를 선택해주세요.

### 업체 생성
POST {{URL}}/companies
Content-Type: application/json

{
  "username": "username_ec41f9c395c4",
  "name": "companyName_0b5e701785a7",
  "companyType": "PRODUCER",
  "address": {
    "roadAddress": "서울특별시 강남구 강남대로 1234",
    "detailAddress": "강남빌딩 1234호",
    "zipcode": "12345"
  }
}

> {%
  client.global.set("COMPANY_ID", response.body.data.id); // HUB_ID 라는 변수에 response.body.data.id 값을 저장
%}


### 업체 리스트 조회
GET {{URL}}/companies

### 업체 단건 조회
GET {{URL}}/companies/{{COMPANY_ID}}

### 업체 수정
PATCH {{URL}}/companies/{{COMPANY_ID}}
Content-Type: application/json

{
  "name": "name_c99d455c0e83",
  "companyStatus": "OPENED",
  "companyType": "RECEIVER",
  "address": {
    "roadAddress": "서울특별시 강남구 강남대로 1234",
    "detailAddress": "강남빌딩 1235호",
    "zipcode": "12345"
  }
}

### 업체 삭제
DELETE {{URL}}/companies/{{COMPANY_ID}}


### 물품 생성
POST {{URL}}/products
Content-Type: application/json

{
  "companyId": "{{COMPANY_ID}}",
  "hubId": "{{HUB_ID}}",
  "name": "플라스틱",
  "price": 10000
}
